### ISSUE TITLE
Auto tracker comes up as inactive

### ISSUE THREAD

**Issue by x10power** [x10power/ffmq-rando-tracker#29]
https://cdn.discordapp.com/attachments/1277628232820199435/1277628570990280734/IMG_2727.jpg?ex=66cddbd4&is=66cc8a54&hm=f8ffc6dbbf518a53ce5d72b6a942f9cb6d0091f28cddd0c15c0442da9351f37d&

**Comment by miketrethewey** [comment]
Fixed here: https://github.com/x10power/ffmq_pack_x10power/blob/unstable/scripts/settings/settings.lua
